// @ts-expect-error — this file is generated by the OpenNext build step and doesn't exist until then
import handler from "./.open-next/worker.js";
import { SheetUpdates } from "./lib/durable-objects/sheet-updates";

export { SheetUpdates };

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    const url = new URL(request.url);

    if (url.pathname === "/api/sheets-stream") {
      const stub = env.SHEET_UPDATES.getByName("global");
      return stub.fetch(request);
    }

    return handler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;
